project:
  type: website
  output-dir: docs


website:
  title: "Emily Montes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutme!.qmd
      - mycv.qmd

format:
  html:
    theme: pulse
    mainfont: arial
    fontsize: 1.3rem
    fontcolor: "#000000"
    linkcolor: "#3498DB"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

