project:
  type: website
  output-dir: docs

website:
  title: "Emily Montes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - aboutme!.qmd
      - mycv.qmd

format:
  html:
    theme: sandstone
    mainfont: arial
    fontsize: 1.5rem
    fontcolor: "#36454F"
    linkcolor: "#702963"
    monofont: courier new
    css: styles.css
    toc: true

editor: visual

